includes:
  - https://github.ibm.com/cloud-docs/cloudant-cli-plugin
# Uncomment the following section if excluding files from translation.
# translation:
#  exclude:
#    byFilePath:
#      - file-dont-translate.md
#      - folder-dont-translate/
